import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/home.module.css";

import HeroImage from '../../public/assets/hero.png'

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Organize suas tarefas</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div
        className={`${styles.container} ${geistSans.variable} ${geistMono.variable}`}
      >
      <main className={styles.main}>
          <div className={styles.logoContent}>
            <Image className={styles.hero}alt='Logo Tarefas'src={HeroImage} priority/>
            <h1 className={styles.title}>Sistema feito para você se organizar <br />Priorize seus estudos.</h1>

            <div className={styles.infoContent}>
              <section className={styles.box}>
                <span>+90 Posts</span>
              </section>
              <section className={styles.box}>
                <span>+12 Comentários</span>
              </section>
            </div>
          
          
          </div>
         
      </main>
      </div>
    </>
  );
}
